server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://teamssac3.cvmsqg9zdlaq.ap-northeast-2.rds.amazonaws.com:3306/ATTENDANCE_MANAGEMENT
    username: admin
    password: qwer1234!





